import { ClerkProvider } from "@clerk/nextjs";
import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import ProfileHeader from "@/utils/header/page";
import { Layout, Menu, theme } from "antd";
import NavigationMenu from "@/utils/slider/page";
import NarrowFooter from "@/utils/footer/page";
import Wrapper from "@/utils/content/page";

const geistSans = localFont({
    src: "./fonts/GeistVF.woff",
    variable: "--font-geist-sans",
    weight: "100 900",
});
const geistMono = localFont({
    src: "./fonts/GeistMonoVF.woff",
    variable: "--font-geist-mono",
    weight: "100 900",
});

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

const { Header, Content, Footer, Sider } = Layout;

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    const APP_NAME: string =
        process.env.NEXT_PUBLIC_APP_NAME || "Default App Name";

    return (
        <ClerkProvider>
            <html lang="en">
                <body
                    className={`${geistSans.variable} ${geistMono.variable} antialiased`}
                >
                    <Layout>
                        <NavigationMenu />
                        <Layout>
                            <ProfileHeader appName={APP_NAME} />
                            <Wrapper>{children}</Wrapper>
                            <NarrowFooter />
                        </Layout>
                    </Layout>
                </body>
            </html>
        </ClerkProvider>
    );
}
